-- Migration Script generated from CSV (48 products - REFACTORED)
-- Generated: 2026-02-09T19:22:39.095Z
-- Eliminates S1192 duplications using DO block with constants

-- 1. Create new columns if they don't exist
ALTER TABLE products ADD COLUMN IF NOT EXISTS usage_area text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS target_audience text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS ingredients text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tips text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size_ml text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size_fl_oz text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS usage text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description_additional text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image2_url text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image3_url text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_filter text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS target_audience text;

-- Ensure ID has a default value for new inserts
CREATE SEQUENCE IF NOT EXISTS products_id_seq;
ALTER TABLE products ALTER COLUMN id SET DEFAULT nextval('products_id_seq');
SELECT setval('products_id_seq', COALESCE((SELECT MAX(id) FROM products), 0) + 1);

-- Refactored: Use DO block with constants
DO $$
DECLARE
    base_url text := 'https://hkedgklpsksezxxymdgc.supabase.co/storage/v1/object/public/images/';
    default_brand text := 'Sexitive';
BEGIN
    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Love Potion Cioccolato', 'love-potion-cioccolato', 'Olio commestibile', default_brand, 12.80, 'Olio commestibile, massaggi in zona intima', 'Creato per trasformare ogni bacio in un''esperienza calda, deliziosa e profondamente sensuale.', 'Curiosità', base_url || 'love-potion-cioccolato.webp', '30 ml', '1.0 fl oz', 'A01', 'Cioccolato', true, base_url || 'love-potion-cioccolato-2.webp', base_url || 'love-potion-cioccolato-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Love Potion Frutti Rossi', 'love-potion-frutti-rossi', 'Olio commestibile', default_brand, 12.80, 'Olio commestibile, massaggi in zona intima', 'Creato per trasformare ogni bacio in un''esperienza calda, deliziosa e profondamente sensuale.', 'Curiosità', base_url || 'love-potion-frutti-rossi.webp', '30 ml', '1.0 fl oz', 'A03', 'Frutti Rossi', true, base_url || 'love-potion-frutti-rossi-2.webp', base_url || 'love-potion-frutti-rossi-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Love Potion Champagne E Lampone', 'love-potion-champagne-e-lampone', 'Olio commestibile', default_brand, 12.80, 'Olio commestibile, massaggi in zona intima', 'Creato per trasformare ogni bacio in un''esperienza calda, deliziosa e profondamente sensuale.', 'Curiosità', base_url || 'love-potion-champagne-e-lampone.webp', '30 ml', '1.0 fl oz', 'A06', 'Champagne e Lampone', true, base_url || 'love-potion-champagne-e-lampone-2.webp', base_url || 'love-potion-champagne-e-lampone-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Love Potion Zucchero Filato', 'love-potion-zucchero-filato', 'Olio commestibile', default_brand, 12.80, 'Olio commestibile, massaggi in zona intima', 'Creato per trasformare ogni bacio in un''esperienza calda, deliziosa e profondamente sensuale.', 'Curiosità', base_url || 'love-potion-zucchero-filato.webp', '30 ml', '1.0 fl oz', 'A27', 'Zucchero Filato', true, base_url || 'love-potion-zucchero-filato-2.webp', base_url || 'love-potion-zucchero-filato-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, image3_url, stock)
    VALUES ('Body Splash Love', 'body-splash-love', 'Fragranza', default_brand, 20.30, 'Body Splash', 'Love Aphrodisiac  avvolge la tua pelle con un profumo che sembra una carezza calda e sensuale, ideale per chi ama un profumo fresco, femminile e provocante.', 'Fresco', base_url || 'body-splash-love.webp', '100 ml', '3.4 fl oz', 'BSN03', true, base_url || 'body-splash-love-2.webp', base_url || 'body-splash-love-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Bali Sunset Stripped', 'bali-sunset-stripped', 'Fragranza', default_brand, 53.6, 'Aphrodisiac Eau de Toilette', 'Una fragranza femminile che gioca con i contrasti: note floreali e dolci si intrecciano in una tensione sensuale, attraversata da una vibrazione salata che risveglia e cattura i sensi.', 'Sensuale', base_url || 'bali-sunset-stripped.webp', 'Nota di testa: accordo salato                                                                                                                                                                                                                                                Nota di cuore: gelsomino                                                                                                                                                                                                                                                      Nota di fondo: meringa', '100 ml', '3.4 fl oz', 'BSS', true, base_url || 'bali-sunset-stripped-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Hot Inevitable', 'hot-inevitable', 'Fragranza', default_brand, 37.8, 'Aphrodisiac Eau de Toilette', 'Una collezione di fragranze irresistibili, dove ogni variante è un invito al desiderio: da quella fruttata e assuefacente, a quella floreale, intensa o misteriosa. Personalità diverse, un''unica intenzione: sedurre senza limiti.', 'Misterioso', base_url || 'hot-inevitable.webp', 'Note di Testa: mango e bergamotto                                                                                                                                                                                                                                     Note di Cuore: gelsomino e incenso di olibano                                                                                                                                                                                                                     Note di Fondo: vaniglia e sandalo', '100 ml', '3.4 fl oz', 'C01', true, base_url || 'hot-inevitable-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Hot Inevitable Privee', 'hot-inevitable-privee', 'Fragranza', default_brand, 37.8, 'Aphrodisiac Eau de Toilette', 'Una collezione di fragranze irresistibili, dove ogni variante è un invito al desiderio: da quella fruttata e assuefacente, a quella floreale, intensa o misteriosa. Personalità diverse, un''unica intenzione: sedurre senza limiti.', 'Elegante', base_url || 'hot-inevitable-privee.webp', 'Note di Testa: pera, pepe rosa e fiore d''arancio                                                                                                                                                                                                                 Note di Cuore: caffè, gelsomino, mandorla                                                                                                                                                                                                                            Note di Fondo: vaniglia e legno di cedro', '100 ml', '3.4 fl oz', 'C01V-1', true, base_url || 'hot-inevitable-privee-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Hot Inevitable So Excited', 'hot-inevitable-so-excited', 'Fragranza', default_brand, 37.8, 'Aphrodisiac Eau de Toilette', 'Una collezione di fragranze irresistibili, dove ogni variante è un invito al desiderio: da quella fruttata e assuefacente, a quella floreale, intensa o misteriosa. Personalità diverse, un''unica intenzione: sedurre senza limiti.', 'Vibrante', base_url || 'hot-inevitable-so-excited.webp', 'Note di Testa: peonia, peach e violetta                                                                                                                                                                                                                                  Note di Cuore: gigli, giglio bianco, giacinto, gelsomino, fresia                                                                                                                                                                                              Note di Fondo: muschio, legno di cedro, ambra', '100 ml', '3.4 fl oz', 'C01V-2', true, base_url || 'hot-inevitable-so-excited-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Body Splash Hot Inevitable', 'body-splash-hot-inevitable', 'Fragranza', default_brand, 20.30, 'Body Splash', 'GIOCOSA. SENSUALE. POTENTE. Hot Inevitable è la fragranza pensata per le donne che vogliono sentirsi irresistibili in ogni movimento. Leggera, fresca e coinvolgente, è perfetta per profumare tutto il corpo e accompagnarti nei tuoi momenti più audaci, divertenti o seducenti.', 'Potente', base_url || 'body-splash-hot-inevitable.webp', '100 ml', '3.4 fl oz', 'C02', true, base_url || 'body-splash-hot-inevitable2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Crazy Girl', 'crazy-girl', 'Fragranza', default_brand, 30.7, 'Aphrodisiac Eau de Toilette', 'Una fragranza creata per le donne que emanano sicurezza e amano il gioco della seduzione. Un profumo fresco, seducente, sensuale e irresistibile', 'Irresistibile', base_url || 'crazy-girl.webp', 'Note di Testa: lampone e limone di Amalfi                                                                                                                                                                                                                            Note di Cuore: gelsomino, fiore d''arancio africano e gardenia                                                                                                                                                                                            Note di Fondo: miele e ambra', '60 ml', '2.0 fl oz', 'C51', true, base_url || 'crazy-girl-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Body Splash Crazy Girl', 'body-splash-crazy-girl', 'Fragranza', default_brand, 20.30, 'Body Splash', 'ESUBERANTE, AVVINCENTE, INDIMENTICABILE. Crazy Girl è una fragranza per le donne che vogliono catturare l''attenzione. Ricca di glamour e personalità, unisce freschezza, dolcezza e un tocco di sensualità che cattura tutti gli sguardi.', 'Glamour', base_url || 'body-splash-crazy-girl.webp', '100 ml', '3.4 fl oz', 'C53', true, base_url || 'body-splash-crazy-girl-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Desire Coconut', 'desire-coconut', 'Lubrificante', default_brand, 13.50, 'Gel lubrificante aromatizzato', 'Progettato per offrire una lubrificazione a lunga durata. Con un squisito aroma di Cocco che si adatta perfettamente alla tua personalità', 'Sensuale', base_url || 'desire-coconut.webp', '75 ml', '2.5 fl oz', 'CT03', 'Anale', true, base_url || 'desire-coconut2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Body Splash Be', 'body-splash-be', 'Fragranza', default_brand, 15.10, 'Body Splash con Glitter', 'BE Aphrodisiac Glitter è uno spray corpo creato per chi ama distinguersi. Il suo profumo irresistibile si unisce a delicati Glitter che illuminano la pelle, creando un effetto radioso e sensuale ad ogni movimento.', 'Glamour', base_url || 'body-splash-be.webp', '60 ml', '2.0 fl oz', 'D04', true, base_url || 'body-splash-be-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Body Splash Privee', 'body-splash-privee', 'Fragranza', default_brand, 15.10, 'Body Splash con Glitter', 'Un splash per il corpo che unisce freschezza, sensualità e luminosità in un unico gesto. Profuma, seduci, illumina… e rendi la tua presenza irresistibile.', 'Glamour', base_url || 'body-splash-privee.webp', '60 ml', '2.0 fl oz', 'D17', true, base_url || 'body-splash-privee-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, image3_url, stock)
    VALUES ('Body Splash So Excited', 'body-splash-so-excited', 'Fragranza', default_brand, 15.10, 'Body Splash con Glitter', 'Accattivante, glamour e pieno di energia. Hot Inevitable So Excited, il body splash creato per chi ama distinguersi, brillare senza sforzo e amare la seduzione a ogni passo. La sua fragranza afrodisiaca, abbinata a Glitter scintillanti, illumina la pelle e avvolge il corpo in un''aura magnetica impossibile da ignorare.', 'Glamour', base_url || 'body-splash-so-excited.webp', '60 ml', '2.0 fl oz', 'D18', true, base_url || 'body-splash-so-excited-2.webp', base_url || 'body-splash-so-excited-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Black Dragon', 'black-dragon', 'Lubrificante', default_brand, 25.2, 'Crema Intensificante', 'L''esclusiva formula di Sexitive, sviluppata con estratti naturali, favorisce una maggiore eccitazione e intensifica la risposta sessuale. Inizia con una sensazione calda e delicata que poi si intensifica profondamente', 'caldo/freddo', base_url || 'black-dragon.webp', 'Appicando la crema Black Dragon, noterai un aumento del desiderio sessuale, acquisirai maggiore sicurezza in te stesso, vivrai il sesso di coppia in modo diverso e raggiungerai livelli di piacere mai provati prima, grazie al suo effetto caldo-freddo. Base aquosa', '50 ml', '1.7 fl oz', 'DRN02', 'vaginale', true, base_url || 'black-dragon-2.webp', base_url || 'black-dragon-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Diva''s Secret - Effetto Caldo', 'diva-s-secret-effetto-caldo', 'Lubrificante', default_brand, 16.4, 'Gel Lubrificante', 'Una volta applicato, genera un aumento della temperatura, massimizzando il piacere.', 'Caldo', base_url || 'diva-s-secret-effetto-caldo.webp', 'Acido Lattico: aiuta a mantenere il naturale equilibrio delle parti intime e aumenta la sensazione di calore.                                                                                                                           Vitamina E: idratante e antiossidante. Ammorbidisce, protegge e lascia una sensazione setosa che aumenta il piacere.                                                                                                       Base acquosa.', '30 ml', '1.0 fl oz', 'DVS01', 'vaginale', true, base_url || 'diva-s-secret-effetto-caldo-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Diva''s Secret Effetto Tightening', 'diva-s-secret-effetto-tightening', 'Lubrificante', default_brand, 18.7, 'Gel Lubrificante', 'Dona una sensazione di compattezza, tonicitá e freschezza alle parte intime. La sua conbinazione di ingredienti attivi di alta qualitá aiuta a rivitalizzare la pelle, migliorandone l´elasticitá e regalando un´esperienza piú tonica, liscia e piacevole.', 'Tightening', base_url || 'diva-s-secret-effetto-tightening.webp', 'Acido Ialuronico: idrata in profonditá e migliora l´elasticitá, lasciando la pelle piú morbida ed elastica.                                                                                                                                         Amamelide (Hamamelis Virginiana): ha proprietá tonificanti e rinfrescante. Aiuta a rafforzare la tonicitá e a donare una maggiore sensazione di comfort.                                                                             Acido Lattico: contribuisce a mantenere il naturale equilibrio delle parte intime e migliora la texture della pelle.                                                                                                                                                         Base acquosa.', '30 ml', '1 fl oz', 'DVS02', 'vaginale', true, base_url || 'diva-s-secret-effetto-tightening-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, image3_url, stock)
    VALUES ('Fucking Fabulous', 'fucking-fabulous', 'Fragranza', default_brand, 42.2, 'Aphrodisiac Eau de Toilette', 'Una fragranza maschile dal carattere fresco e sofisticato. Le note agrumate donano energia e vitalità, mentre i legni nobili conferiscono profondità ed eleganza.', 'Seduttore', base_url || 'fucking-fabulous.webp', 'Note di testa: pompelmo, lime, menta e pepe rosa                                                                                                                                                                                                               Note di cuore: zenzero, vetiver e gelsomino                                                                                                                                                                                                                       Note di fondo: incenso di olibano e legno di cedro', '100 ml', '3.4 fl oz', 'FBLS', true, base_url || 'fucking-fabulous-2.webp', base_url || 'fucking-fabulous-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('For Him', 'for-him', 'Fragranza', default_brand, 33.2, 'Aphrodisiac Eau de Toilette', 'ISPIRATO A UN UOMO DISTINTO, MISTERIOSO E SENSUALE. Un ritratto olfattivo per l''amante sicuro di sé, capace di proiettare la forza iconica dell''attrazione sessuale', 'Sicuro', base_url || 'for-him.webp', 'Note di Testa: mela verde, lavanda                                                                                                                                                                                                                                        Note di Fondo: abete, legno di cedro', '100 ml', '3.4 fl oz', 'FH', true, base_url || 'for-him-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('For Him Vip', 'for-him-vip', 'Fragranza', default_brand, 33.2, 'Aphrodisiac Eau de Toilette', 'IL PROFUMO DELLA SEDUZIONE Una fragranza dallo spirito audace, intenso e irresistibile', 'Audace', base_url || 'for-him-vip.webp', 'Note di Testa: limone, zenzero e menta                                                                                                                                                                                                                                   Note di Fondo: Fava Tonka e Amberwood', '100 ml', '3.4 fl oz', 'FH02', true, base_url || 'for-him-vip-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Love Play', 'love-play', 'Gioco', default_brand, 17.10, 'Gioco di dadi', 'Include 3 dadi da gioco: 1 dado rappresenta la velocità, un altro i luoghi e l''altro le posizioni.', 'Libertà', base_url || 'love-play.webp', 'GLO01', 'Dadi', true, base_url || 'love-play-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Secret Game', 'secret-game', 'Gioco', default_brand, 17.10, 'Gioco di dadi', 'Include 3 dadi, un dado rappresenta il tempo, un altro le azioni e il terzo i luoghi.', 'Libertà', base_url || 'secret-game.webp', 'GLO02', 'Dadi', true, base_url || 'secret-game-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Mini Poker', 'mini-poker', 'Gioco', default_brand, 8.90, 'Gioco di poker erotico', 'Contiene 50 carte con posizioni sessuali. Formato mini, comodo da portare ovunque.', 'Piccante', base_url || 'mini-poker.webp', 'GLO19', 'Carte', true, base_url || 'mini-poker-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Party Game', 'party-game', 'Gioco', default_brand, 12.80, 'Gioco di dadi amici', 'Contiene 3 dadi a tema, azioni, intensità o sfide diverse.', 'Confidenza', base_url || 'party-game.webp', 'GLO20', 'Dadi', true, base_url || 'party-game-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Oh My God', 'oh-my-god', 'Gioco', default_brand, 9.30, 'Gioco di dadi coppia', 'Contiene 2 dadi. Un dado con le azioni e un altro con le parti del corpo.', 'Confidenza', base_url || 'oh-my-god.webp', 'GLO21', 'Dadi', true, base_url || 'oh-my-god-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, code, ingredients, active, image2_url, image3_url, stock)
    VALUES ('Hi Sex Bustina', 'hi-sex-bustina', 'Vigorizzanti', default_brand, 7, 'Integratore naturale', 'È un afrodisiaco naturale, ma anche un invito a riconnetterti con la tua essenza, a risvegliare il tuo desiderio e a vivere la tua intimità in modo pieno e consapevole. La sua formula combina il potere di ingredienti millenari que rivitalizzano il corpo, potenziano l''energia e migliorano le prestazioni sessuali', 'Vitalizzante', base_url || 'hi-sex-bustina.webp', 'Aumenta l´appetito sessuale e migliora gli orgasmi.                                                                                                                                                                                                      Promuove una sensazione di appagamento emotivo.                                                                                                                                                                                                       Migliora la circolazione nella zona genitale.                                                                                                                                                                                                                  Aumenta energia, vitalitáe desiderio.                                                                                                                                                                                                                               Formula equilibrata, completa e efficace.', '60 CAPS', 'HSX-AE- 001', 'L-Arginina - Damiana - Maca - Tribulus - Ginko - Zinc - Vitamina V6', true, base_url || 'hi-sex-bustina-2.webp', base_url || 'hi-sex-bustina-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, ingredients=EXCLUDED.ingredients, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, code, ingredients, active, image2_url, image3_url, stock)
    VALUES ('Hi Sex Pote', 'hi-sex-pote', 'Vigorizzanti', default_brand, 69.7, 'Integratore naturale', 'È un afrodisiaco naturale, ma anche un invito a riconnetterti con la tua essenza, a risvegliare il tuo desiderio e a vivere la tua intimità in modo pieno e consapevole. La sua formula combina il potere di ingredienti millenari que rivitalizzano il corpo, potenziano l''energia e migliorano le prestazioni sessuali', 'Vitalizzante', base_url || 'hi-sex-pote.webp', 'Aumenta l´appetito sessuale e migliora gli orgasmi.                                                                                                                                                                                                      Promuove una sensazione di appagamento emotivo.                                                                                                                                                                                                       Migliora la circolazione nella zona genitale.                                                                                                                                                                                                                  Aumenta energia, vitalitáe desiderio.                                                                                                                                                                                                                               Formula equilibrata, completa e efficace.', '4 CAPS', 'HSX-AE- 003', 'L-Arginina - Damiana - Maca - Tribulus - Ginko - Zinc - Vitamina V6', true, base_url || 'hi-sex-pote-2.webp', base_url || 'hi-sex-pote-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, ingredients=EXCLUDED.ingredients, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Ibiza', 'ibiza', 'Fragranza', default_brand, 49.6, 'Aphrodisiac Eau de Toilette', 'Una fragranza unisex, sensuale e vibrante. Come una brezza marina carica di desiderio, risveglia i sensi con una freschezza agrumata e un cuore morbido che evolve in un fondo caldo e irresistibile. Creata per sedurre, senza regole né generi.', 'Vibrante', base_url || 'ibiza.webp', 'Note di Testa: fiore di tè dolce e lime                                                                                                                                                                                                                                   Note di Cuore: ambra grigia, iris e note terrose                                                                                                                                                                                                                   Note di Fondo: cuoio, iris e vaniglia', '100 ml', '3.4 fl oz', 'IBZ', true, base_url || 'ibiza-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Inlube Game', 'inlube-game', 'Gioco', default_brand, 15.40, 'Gioco di dadi + lubrificante', 'Contiene 2 dadi e 1 lubrificante. Il giocatore dovrà compiere una azione determinata sulla parte del corpo indicata dal dado.', 'Divertente', base_url || 'inlube-game.webp', '20 ml', '0.7 fl oz', 'ILG', 'Dadi', true, base_url || 'inlube-game-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Inevitable Men Aphrodisiac', 'inevitable-men-aphrodisiac', 'Fragranza', default_brand, 33.2, 'Aphrodisiac Eau de Toilette', 'Niente è più intenso di Inevitable', 'Intenso', base_url || 'inevitable-men-aphrodisiac.webp', 'Note di Testa: pompelmo, cardamomo e coriandolo                                                                                                                                                                                                                 Nota di Cuore: assenzio, geranio, artemisia e mango                                                                                                                                                                                                             Nota di Fondo: vetiver, legno di guaiaco e fava tonka', '100 ml', '3.4 fl oz', 'IN01', true, base_url || 'inevitable-men-aphrodisiac-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Inevitable Men Vip Aphrodisiac', 'inevitable-men-vip-aphrodisiac', 'Fragranza', default_brand, 33.2, 'Aphrodisiac Eau de Toilette', 'Niente è più intenso di Inevitable', 'Misterioso', base_url || 'inevitable-men-vip-aphrodisiac.webp', 'Note di Testa: incenso di Kyara                                                                                                                                                                                                                                           Note di Cuore: ambra e fava tonka                                                                                                                                                                                                                                            Note di Fondo: vaniglia, cuoio e note legnose', '100 ml', '3.4 fl oz', 'IN02', true, base_url || 'inevitable-men-vip-aphrodisiac-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, image3_url, stock)
    VALUES ('It Femme', 'it-femme', 'Fragranza', default_brand, 32.7, 'Aphrodisiac Eau de Toilette', 'Il calore narcotico della vaniglia libera il suo istinto carnale. Un aroma orientale-floreale, provocante e selvaggio, que cattura, accelera ed esalta i sensi. Un risultato magnetico.', 'Selvaggio', base_url || 'it-femme.webp', 'Note di Testa: Ylang-Ylang e vaniglia                                                                                                                                                                                                                                  Note di Cuore: Legno di sandalo                                                                                                                                                                                                                                          Note di Fondo: Popcorn', '60 ml', '2.0 fl oz', 'IT01', true, base_url || 'it-femme-2.webp', base_url || 'it-femme-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('It Femme Florale', 'it-femme-florale', 'Fragranza', default_brand, 32.7, 'Aphrodisiac Eau de Toilette', 'Immergiti in una tentazione irresistibile con questa fragranza provocante e seducente, dal contrasto audace e affascinante. È un profumo creato per chi non passa inosservata', 'Provocante', base_url || 'it-femme-florale.webp', 'Note di Testa: bergamotto, agrumi e pera                                                                                                                                                                                                                            Note di Cuore: gelsomino, ylang ylang e legno di palissandro                                                                                                                                                                                             Note di Fondo: vaniglia, fava tonka e legno di cedro', '60 ml', '2.0 fl oz', 'IT02', true, base_url || 'it-femme-florale-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, image3_url, stock)
    VALUES ('Lube Premium Relaxing', 'lube-premium-relaxing', 'Lubrificante', default_brand, 16.4, 'Gel Lubrificante Anale Con Jojoba E Camomilla', 'Lubrificante personale a base acquosa, con estratti di jojoba che ha propietá idratanti ed emollienti che proteggono la pelle e favoriscono una scorrevolezza piú naturale e camomilla che fornisce calma, freschezza e una sensazione rilassante che contribuisce a migliorare il comfort durante l´uso.', 'Rilassante', base_url || 'lube-premium-relaxing.webp', 'MASSIMO COMFORT, ideale per chi cerca un''esperienza anale più fluida e piacevole.                                                                                                                                                     TEXTURE SETOSA E DURATURA, senza sensazione appiccicosa.                                                                                                                                                                                      INGREDIENTI NATURALI, che si prendono cura e proteggono la pelle.                                                                                                                                                                         SENSAZIONE RILASSANTE, perfetta per principianti ed esperti.', '130 ml', '4.4 fl oz', 'LUB01', 'anale', true, base_url || 'lube-premium-relaxing-2.webp', base_url || 'lube-premium-relaxing-3.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, image3_url=EXCLUDED.image3_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Lube Intensity Hot Pleasure', 'lube-intensity-hot-pleasure', 'Lubrificante', default_brand, 19.2, 'Gel Lubrificante Anale Con Effetto Caldo', 'Lubrificante personale a base acquosa, ideale per chi cerca il piacere intenso. Il suo effetto caldo attiva la sensibilitá della pelle dal primo contatto, potenziando ogni movimento e creando una sperienza intima piú vibrante.', 'Caldo', base_url || 'lube-intensity-hot-pleasure.webp', 'EFFETTO CALDO immediato.                                                                                                                                                                                                                                         TEXTURE SETOSA E DURATURA, senza sensazione appiccicosa.                                                                                                                                                                          SENSAZIONE CALDA E AVVOLGENTE, perfetta per intensificare.', '130 ml', '4.4 fl oz', 'LUB02', 'anale', true, base_url || 'lube-intensity-hot-pleasure-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Lube Supreme Retardante', 'lube-supreme-extra-time', 'Lubrificante', default_brand, 16.4, 'Gel Lubrificante Anale Ritardante Con Effetto Freddo Per Relazioni Più Lunghe', 'Lubrificante personale a base acquosa con Mentolo che offre un effetto rinfrescante immediato, rinfrescante e stimolante che aumenta la sensibilità e il piacere. A base in gel premium con una texture liscia e scorrevole che si assorbe rapidamente e non lascia una sensazione appiccicosa. L''effetto di ritardo sensoriale offre un maggiore senso di controllo, aiutando a prolungare i momenti intimi in modo naturale e piacevole.', 'Freddo', base_url || 'lube-supreme-extra-time.webp', 'Una sensazione sensoriale RITARDANTE, ideale per prolungare l''esperienza. 
Un effetto RINFRESCANTE stimolante che rinfresca e aggiunge un tocco vibrante.                                                                                                                                                                Texture setosa e lubrificazione superiore.
Ideale per l''uso in coppia o da soli.', '130 ml', '4.4 fl oz', 'LUB03', 'anale', true, base_url || 'lube-supreme-extra-time-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Mine My Pleasure', 'mine-my-pleasure', 'Lubrificante', default_brand, 15, 'Gel Lubrificante', 'Gel lubrificante con L-Arginina, un amminoacido di origine naturale con capacità vasodilatatrice, specificamente formulato per aumentare l''eccitazione e la sensibilità del clitoride, favorendo orgasmi più intensi e veloci.', 'Intenso', base_url || 'mine-my-pleasure.webp', 'Sensibilitá migliorata: ideale per intensificare i preliminari e gli incontri intimi.                                                                                                                                                                                                   L-Arginina: stimola la circolazione per sensazioni piú profonde.                                                                                                                                                                                                                       Acido Lattico: mantiene il pH intimo e dona confort.                                                                                                                                                                                                                                               Base aquosa.', '50 ml', '1.7 fl oz', 'MMP', 'vaginale', true, base_url || 'mine-my-pleasure2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('More Sex - Berries', 'more-sex-berries', 'Lubrificante', default_brand, 21.9, 'Gel Lubrificante', 'Goditi un delizioso sesso orale con una sensazione unica', 'Dolce', base_url || 'more-sex-berries.webp', 'Texture leggera, setosa e la scorrevolezza a lunga durata garantiscono comfort e fluitá a ogni movimento. Base acquosa', '50 ml', '1.7 fl oz', 'MMSB', 'vaginale', true, base_url || 'more-sex-berries2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('More Sex - Chocolate', 'more-sex-chocolate', 'Lubrificante', default_brand, 21.9, 'Gel Lubrificante', 'Dimostra al partner que hai buon gusto. Questo lubrificante è stato creato per aggiungere sapore e migliorare il sesso orale.', 'Dolce', base_url || 'more-sex-chocolate.webp', 'Texture leggera, setosa e la scorrevolezza a lunga durata garantiscono comfort e fluitá a ogni movimento. Base acquosa', '50 ml', '1.7 fl oz', 'MMSC', 'vaginale', true, base_url || 'more-sex-chocolate-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Very Sexy', 'very-sexy', 'Fragranza', default_brand, 29.2, 'Aphrodisiac Eau de Toilette', 'Questo profumo non si indossa, si conquista. Pensato per la donna que non chiede permesso, que trasforma gli sguardi in desideri e i momenti in ricordi.Non è solo un profumo. È una dichiarazione d''intenti.', 'Provocante', base_url || 'very-sexy.webp', 'Note di Testa: mandorla, caffè, bergamotto e limone                                                                                                                                                                                                           Note di Cuore: tuberosa, gelsomino, fiore d''arancio, iris e rosa bulgara                                                                                                                                                                              Note di Fondo: cacao, vaniglia e cannella', '50 ml', '1.7 fl oz', 'PLS', true, base_url || 'very-sexy2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Body Splash Petit Mort', 'body-splash-petit-mort', 'Fragranza', default_brand, 20.30, 'Body Splash', 'Fresco, giovane e deliziosamente irresistibile. Petit Mort è un profumo per il corpo che unisce energia, sensualità e gioia in una fragranza orientale floreale-fruttata che invita a sentirsi liberi, vibranti e assolutamente irresistibili.', 'Irresistibile', base_url || 'body-splash-petit-mort.webp', '100 ml', '3.4 fl oz', 'PM02', true, base_url || 'body-splash-petit-mort-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, active, image2_url, stock)
    VALUES ('Petit Mort', 'petit-mort', 'Fragranza', default_brand, 29.2, 'Aphrodisiac Eau de Toilette', 'È una fragranza floreale e legnosa, con un aroma allegro, giovanile, fresco e puro que trasmette un''indescrivibile sensazione di libertà.', 'Libero', base_url || 'petit-mort.webp', 'Note di Testa: mela, mandarino e magnolia                                                                                                                                                                                                                          Note di Cuore: ribes bianco, peonia e gelsomino                                                                                                                                                                                                                 Note di Fondo: muschio e Amberwood', '50 ml', '1.7 fl oz', 'PM03', true, base_url || 'petit-mort2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Sens Bomb Maca', 'sens-bomb-maca', 'Lubrificante', default_brand, 13.9, 'Gel Intimo Con Estratti Natural', 'Tutto il potere afrodisiaco della Maca concentrato in questo gel intimo femminile, que offre stimolazione, attivazione e potenzamiento della sensibilitá intima.', 'Caldo', base_url || 'sens-bomb-maca.webp', 'Effetto riscaldante estimulante, aumenta il piacere. Di texture morbida e liscia. Base acquosa.', '70 ml', '2.4 fl oz', 'SENS-BOMB-MACA', 'vaginale', true, base_url || 'sens-bomb-maca2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, description_additional, size_ml, size_fl_oz, code, product_filter, active, image2_url, stock)
    VALUES ('Sens Bomb Sandalo', 'sens-bomb-sandalo', 'Lubrificante', default_brand, 13.9, 'Gel Intimo Con Estratti Natural', 'La sua formula stimolante e afrodisiaco, il Sandalo Rosso transforma ogni carezza in un´ondata de caldo e avvolgente piacere. Appena aplicato, il gel inizia ad attivare la pelle, un calore progressivo, delizioso e profondamente eccitante che aumenta la sensibilitá e rende l´incontro un´esperienza piú intensa e passionale.', 'Caldo', base_url || 'sens-bomb-sandalo.webp', 'Effetto riscaldante attiva, stimola e aumenta il piacere. Aumenta la sensibilitá. Sandalo rosso, aroma caldo, sensuale e profondamente erotico. Base acquosa.', '70 ml', '2.4 fl oz', 'SENS-BOMB-SANDALO', 'vaginale', true, base_url || 'sens-bomb-sandalo-2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, description_additional=EXCLUDED.description_additional, size_ml=EXCLUDED.size_ml, size_fl_oz=EXCLUDED.size_fl_oz, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Sex Roulette Party Game', 'sex-roulette-party-game', 'Gioco', default_brand, 17.10, 'Gioco roulette', 'Roulette erotica pensata per gruppi  che vogliono giocare, ridere e lasciarsi trasportare da sfide sempre più piccanti.', 'Sfida', base_url || 'sex-roulette-party-game.webp', 'SRP01', 'Roulette', true, base_url || 'sex-roulette-pary-game2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

    INSERT INTO products (name, slug, category, brand, price, subtitle, description, sensation, image_url, code, product_filter, active, image2_url, stock)
    VALUES ('Sex Roulette Lovers Game', 'sex-roulette-lovers-game', 'Gioco', default_brand, 17.10, 'Gioco roulette', 'Gioco erotico che transforma ogni giro in una sfida emozionante. Ideale per creare momenti intensi, risate, connessione e tanto divertimento bollente.', 'Sfida', base_url || 'sex-roulette-lovers-game.webp', 'SRP02', 'Roulette', true, base_url || 'sex-roulette-lovers-game2.webp', 0)
    ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, slug=EXCLUDED.slug, category=EXCLUDED.category, brand=EXCLUDED.brand, price=EXCLUDED.price, subtitle=EXCLUDED.subtitle, description=EXCLUDED.description, sensation=EXCLUDED.sensation, image_url=EXCLUDED.image_url, product_filter=EXCLUDED.product_filter, active=EXCLUDED.active, image2_url=EXCLUDED.image2_url, stock=EXCLUDED.stock;

END $$;
